server:
  servlet:
    context-path: /zyl
  port: 6789
  tomcat:
    uri-encoding: utf-8



logging:
  level:
    root: info

fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 39.107.252.103:22122